name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: recursive

            -   name: Hugo Setup
                uses: peaceiris/actions-hugo@v2.4.13

            -   name: Run Hugo
                run: hugo --gc --minify

            -   name: Install SSH Client 🔑
                uses: webfactory/ssh-agent@v0.5.2
                with:
                    ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

            -   name: Deploy to GitHub Pages
                uses: JamesIves/github-pages-deploy-action@4.1.3
                with:
                    branch: master
                    folder: public
                    repository-name: ozyinc/ozyinc.github.io
                    ssh: true
