name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: recursive

            -   name: Hugo Setup
                uses: peaceiris/actions-hugo@v3
                with:
                    hugo-version: 'latest'
                    extended: true

            -   name: Run Hugo
                run: hugo --gc --minify

            -   name: Deploy to GitHub Pages
                uses: JamesIves/github-pages-deploy-action@4.6.1
                with:
                    branch: master
                    folder: public
                    repository-name: ozyinc/ozyinc.github.io
                    ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
